# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do

  desc "Run the static analyzer on the iOS project"
  lane :analyze do
    analyze
    # TODO: Analyze Mac as well, once this is running on Jenkins
  end

  desc "Create new screenshots for the App Store in all languages and device types"
  desc "Additionally, this will add device frames around the screenshots and add the correct titles"
  lane :screenshots do
    frameit(white: true, path: './fastlane/screenshots')
  end
end
